In [46]:
import numpy as np
import pandas as pd

In [47]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [48]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [49]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [50]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [51]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [52]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [53]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

L_layer_forward(X,parameters)

(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [54]:
(y-0.32)**2

np.float64(13.5424)

In [55]:
y_hat=y_hat[0][0]

In [56]:
A1

array([[1.6],
       [1.6]])

In [57]:
def update_parameters(parameters, y, y_hat, A1, X):
    lr = 0.01 # Learning rate

    # Update W2 (weights for output layer)
    # dLoss/dW2[0][0] = -2 * (y - y_hat) * A1[0][0]
    parameters['W2'][0][0] = parameters['W2'][0][0] + (lr * 2 * (y - y_hat) * A1[0][0])
    # dLoss/dW2[1][0] = -2 * (y - y_hat) * A1[1][0]
    parameters['W2'][1][0] = parameters['W2'][1][0] + (lr * 2 * (y - y_hat) * A1[1][0])

    # Update b2 (bias for output layer)
    # dLoss/db2[0][0] = -2 * (y - y_hat)
    parameters['b2'][0][0] = parameters['b2'][0][0] + (lr * 2 * (y - y_hat))

    # Update W1 and b1 (weights and bias for hidden layer)
    # Gradient chain rule: dLoss/dW1 = dLoss/dA1 * dA1/dW1
    # dLoss/dA1[0][0] = -2 * (y - y_hat) * W2[0][0]
    common_term_for_A1_0_grad = lr * 2 * (y - y_hat) * parameters['W2'][0][0]

    # dLoss/dW1[0][0] = common_term_for_A1_0_grad * X[0][0]
    parameters['W1'][0][0] = parameters['W1'][0][0] + (common_term_for_A1_0_grad * X[0][0])
    # dLoss/dW1[0][1] = common_term_for_A1_0_grad * X[1][0]
    parameters['W1'][0][1] = parameters['W1'][0][1] + (common_term_for_A1_0_grad * X[1][0])
    # dLoss/db1[0][0] = common_term_for_A1_0_grad * 1
    parameters['b1'][0][0] = parameters['b1'][0][0] + (common_term_for_A1_0_grad)

    # dLoss/dA1[1][0] = -2 * (y - y_hat) * W2[1][0]
    common_term_for_A1_1_grad = lr * 2 * (y - y_hat) * parameters['W2'][1][0]

    # dLoss/dW1[1][0] = common_term_for_A1_1_grad * X[0][0]
    parameters['W1'][1][0] = parameters['W1'][1][0] + (common_term_for_A1_1_grad * X[0][0])
    # dLoss/dW1[1][1] = common_term_for_A1_1_grad * X[1][0]
    parameters['W1'][1][1] = parameters['W1'][1][1] + (common_term_for_A1_1_grad * X[1][0])
    # dLoss/db1[1][0] = common_term_for_A1_1_grad * 1
    parameters['b1'][1][0] = parameters['b1'][1][0] + (common_term_for_A1_1_grad)

    return parameters

In [58]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.22821709, 0.22821709],
        [0.22821709, 0.22821709]]),
 'b1': array([[0.01602714],
        [0.01602714]]),
 'W2': array([[0.21776],
        [0.21776]]),
 'b2': array([[0.0736]])}

In [59]:
update_parameters(parameters,y,y_hat,A1,X)

{'W1': array([[0.42577126, 0.42577126],
        [0.42577126, 0.42577126]]),
 'b1': array([[0.04072141],
        [0.04072141]]),
 'W2': array([[0.33552],
        [0.33552]]),
 'b2': array([[0.1472]])}

In [60]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.43894722, 0.44271178],
        [0.43894722, 0.44271178]]),
 'b1': array([[0.04260369],
        [0.04260369]]),
 'W2': array([[0.37035021],
        [0.37035021]]),
 'b2': array([[0.15228243]])}

In [61]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.47118707, 0.49644486],
        [0.4712377 , 0.49652924]]),
 'b1': array([[0.047977  ],
        [0.04798543]]),
 'W2': array([[0.45398047],
        [0.45469338]]),
 'b2': array([[0.16411842]])}

In [62]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.44771447, 0.44011062],
        [0.44811666, 0.44103875]]),
 'b1': array([[0.04328248],
        [0.04336123]]),
 'W2': array([[0.34400532],
        [0.33885296]]),
 'b2': array([[0.15047177]])}

In [65]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  8.557069800197466
Epoch -  2 Loss -  1.2726939416898952e+75
Epoch -  3 Loss -  nan
Epoch -  4 Loss -  nan
Epoch -  5 Loss -  nan


/tmp/ipython-input-4217848365.py:17: RuntimeWarning: overflow encountered in scalar multiply
  common_term_for_A1_0_grad = lr * 2 * (y - y_hat) * parameters['W2'][0][0]
/tmp/ipython-input-4217848365.py:27: RuntimeWarning: overflow encountered in scalar multiply
  common_term_for_A1_1_grad = lr * 2 * (y - y_hat) * parameters['W2'][1][0]
/tmp/ipython-input-174115405.py:23: RuntimeWarning: overflow encountered in scalar power
  Loss.append((y-y_hat)**2)
/tmp/ipython-input-4217848365.py:6: RuntimeWarning: invalid value encountered in scalar add
  parameters['W2'][0][0] = parameters['W2'][0][0] + (lr * 2 * (y - y_hat) * A1[0][0])
/tmp/ipython-input-4217848365.py:8: RuntimeWarning: invalid value encountered in scalar add
  parameters['W2'][1][0] = parameters['W2'][1][0] + (lr * 2 * (y - y_hat) * A1[1][0])
/tmp/ipython-input-4217848365.py:12: RuntimeWarning: invalid value encountered in scalar add
  parameters['b2'][0][0] = parameters['b2'][0][0] + (lr * 2 * (y - y_hat))


{'W1': array([[nan, nan],
        [nan, nan]]),
 'b1': array([[nan],
        [nan]]),
 'W2': array([[nan],
        [nan]]),
 'b2': array([[nan]])}

In [66]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [68]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [70]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [71]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [72]:
model.get_weights()

[array([[ 0.83723533, -0.97263277],
        [ 1.2156433 , -1.105112  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.46870935],
        [-1.1484203 ]], dtype=float32),
 array([0.], dtype=float32)]

In [77]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [75]:
model.set_weights(new_weights)

In [76]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [78]:
model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01), loss='mean_squared_error')

In [79]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [80]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 34.2436  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 24.1348 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.0621 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.2268 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 31.7410 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.4209 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25.4960 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 29.3372 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.7819 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.3813 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.1619 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 20.6117
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.7554 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.1861 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.6666 
Epoch 16/75
4/4 ━━

In [81]:
model.get_weights()

[array([[0.3737631 , 0.3737631 ],
        [0.36559886, 0.36559886]], dtype=float32),
 array([0.2723681, 0.2723681], dtype=float32),
 array([[0.37296972],
        [0.37296972]], dtype=float32),
 array([0.20469634], dtype=float32)]